"""
Surface Physics Engine — Boundary Layer Corrections

Implements three core surface physics functions for the microclimate pipeline:

1. apply_forest_displacement — Displaced log-law wind profile for forested terrain
2. apply_uhi_boundary_layer — Exponential UHI temperature decay with altitude
3. compute_tke — Turbulence kinetic energy from roughness contrast

These functions model the effects of surface roughness and urban heat on the
lower atmosphere (0–1,000 ft AGL), critical for aviation safety and microclimate
forecasting.
"""

import numpy as np
from src.config import VON_KARMAN, UHI_BL_DECAY_HEIGHT_FT, Z0_RURAL_REFERENCE


def apply_forest_displacement(
    wind_speed_ms: float,
    z_agl_m: float,
    z0: float,
    d: float,
    u_star: float,
) -> float:
    """
    Compute wind speed at height z using displaced log-law wind profile.

    Over forests and dense vegetation, the effective ground level is shifted
    upward by the displacement height d (typically 15–18 m for PNW conifers).
    The wind profile becomes:

        u(z) = (u_star / κ) × ln((z − d) / z0)

    where κ is the Von Kármán constant (0.41).

    Below the displacement height (z < d), wind speed is set to zero (within-canopy).

    Parameters
    ----------
    wind_speed_ms : float
        Reference wind speed at a known height (typically 10 m AGL), in m/s.
        Used to compute u_star if not provided directly.
    z_agl_m : float
        Target altitude above ground level, in meters.
    z0 : float
        Roughness length, in meters (from NLCD surface properties).
    d : float
        Displacement height, in meters (from NLCD displacement height lookup).
    u_star : float
        Friction velocity, in m/s. If zero or None, computed from wind_speed_ms
        and reference height (10 m).

    Returns
    -------
    float
        Wind speed at height z_agl_m, in m/s. Returns 0.0 if z_agl_m < d.

    Notes
    -----
    - If z_agl_m < d, returns 0.0 (within-canopy wind is negligible).
    - If z_agl_m == d, returns 0.0 (singularity in log-law at displacement height).
    - If u_star is 0 or None, assumes reference wind at 10 m AGL and computes
      u_star = wind_speed_ms × κ / ln(10 / z0).
    """
    # Within-canopy: wind speed is zero
    if z_agl_m <= d:
        return 0.0

    # Compute friction velocity if not provided
    if u_star is None or u_star == 0:
        # Assume reference wind at 10 m AGL
        z_ref = 10.0
        if z_ref <= d or z0 <= 0:
            return 0.0
        u_star = wind_speed_ms * VON_KARMAN / np.log((z_ref - d) / z0)

    # Displaced log-law wind profile
    if z0 <= 0:
        return 0.0

    wind_speed = (u_star / VON_KARMAN) * np.log((z_agl_m - d) / z0)
    return max(0.0, wind_speed)


def apply_uhi_boundary_layer(
    uhi_offset_f: float,
    z_agl_ft: float,
) -> float:
    """
    Compute UHI temperature offset at altitude using exponential decay.

    Urban heat island effects are strongest at the surface and decay exponentially
    with altitude. The UHI offset at height z is:

        uhi_offset(z) = uhi_offset_f × exp(−z / H_bl)

    where H_bl is the UHI boundary layer decay height (300 ft AGL for PNW).

    Above 1,000 ft AGL, the UHI offset is negligible and set to zero.

    Parameters
    ----------
    uhi_offset_f : float
        Surface-level UHI temperature offset, in °F.
    z_agl_ft : float
        Altitude above ground level, in feet.

    Returns
    -------
    float
        UHI temperature offset at height z_agl_ft, in °F.

    Notes
    -----
    - At z = 0 (surface), returns uhi_offset_f.
    - At z = H_bl (300 ft), returns uhi_offset_f × exp(−1) ≈ 0.368 × uhi_offset_f.
    - At z ≥ 1,000 ft, returns 0.0 (UHI effect negligible above 1,000 ft).
    - Negative uhi_offset_f values are allowed (e.g., rural areas with negative offset).
    """
    # UHI effect negligible above 1,000 ft AGL
    if z_agl_ft >= 1000.0:
        return 0.0

    # Exponential decay with altitude
    decay_factor = np.exp(-z_agl_ft / UHI_BL_DECAY_HEIGHT_FT)
    return uhi_offset_f * decay_factor


def compute_tke(
    u_star: float,
    z0_local: float,
) -> float:
    """
    Compute turbulence kinetic energy (TKE) from friction velocity and roughness.

    TKE is a measure of mechanical turbulence generated by surface roughness.
    Developed areas (urban) generate more TKE than rural areas due to higher
    roughness length (z0). The TKE is computed as:

        TKE = 0.5 × u_star² × (1 + 2 × (z0_local / z0_rural))

    This formula scales TKE with both wind speed (u_star²) and the roughness
    contrast between the local surface and a rural reference (z0_rural = 0.03 m).

    Parameters
    ----------
    u_star : float
        Friction velocity, in m/s. Typically computed from surface wind speed
        and roughness length using the log-law wind profile.
    z0_local : float
        Local roughness length, in meters (from NLCD surface properties).

    Returns
    -------
    float
        Turbulence kinetic energy, in m²/s².

    Notes
    -----
    - TKE is always non-negative.
    - Over smooth surfaces (z0_local ≈ z0_rural), TKE ≈ 0.5 × u_star².
    - Over rough surfaces (z0_local >> z0_rural), TKE increases with roughness contrast.
    - For aviation safety, TKE is mapped to turbulence categories:
      - smooth: TKE < 0.5 m²/s²
      - light: 0.5 ≤ TKE < 1.5 m²/s²
      - moderate: 1.5 ≤ TKE < 3.0 m²/s²
      - severe: TKE ≥ 3.0 m²/s²
    """
    if u_star < 0 or z0_local < 0:
        return 0.0

    # Roughness contrast factor
    roughness_factor = 1.0 + 2.0 * (z0_local / Z0_RURAL_REFERENCE)

    # TKE from friction velocity and roughness
    tke = 0.5 * (u_star ** 2) * roughness_factor

    return max(0.0, tke)
